---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.2
  - name: opentable/win-2012r2-standard-amd64-nocm
    os_type: windows
    shell_type: powershell
    driver:
      gui: true
      box: opentable/win-2012r2-standard-amd64-nocm
      box_url: https://atlas.hashicorp.com/opentable/boxes/win-2012r2-standard-amd64-nocm
    transport:
      name: winrm
      elevated: true

suites:
  - name: windows2012r2
    excludes: centos-7.2
    run_list:
      # - recipe[windows_patch_compliance::windows_patch]
    attributes:
    verifier:
      inspec_tests:
        - https://github.com/chris-rock/windows-patch-benchmark
    driver:
      network:
        - ['private_network', {ip: '33.33.33.30'}]
      customize:
        memory: 2048
        cpus: 2

  - name: compliance
    excludes: opentable/win-2012r2-standard-amd64-nocm
    run_list:
      - recipe[windows_patch_compliance::compliance]
    attributes:
    driver:
      vm_hostname: compliance.patch.io
      network:
        - ['private_network', {ip: '33.33.33.40'}]
      customize:
        memory: 1024
        cpus: 1
